export type AppThemeMode = 'light' | 'dark'
export type AppThemePreset = 'mulberry' | 'studio' | 'graphite' | 'ocean' | 'forest' | 'dawn'

export type ThemeCssVars = Record<`--${string}`, string>

type ThemePreviewPalette = {
  rail: string
  canvas: string
  card: string
  accent: string
  accentSoft: string
  text: string
}

export type ThemePresetDefinition = {
  id: AppThemePreset
  label: string
  description: string
  swatches: [string, string, string]
  preview: Record<AppThemeMode, ThemePreviewPalette>
  cssVars: Record<AppThemeMode, ThemeCssVars>
}

export const DEFAULT_APP_THEME_PRESET: AppThemePreset = 'mulberry'

const PRESET_DEFINITIONS: Record<AppThemePreset, ThemePresetDefinition> = {
  mulberry: {
    id: 'mulberry',
    label: '桑葚',
    description: '极简黑白灰，克制而专注',
    swatches: ['#18181b', '#71717a', '#fafafa'],
    preview: {
      light: {
        rail: '#f1f2f4',
        canvas: '#ffffff',
        card: '#ffffff',
        accent: '#18181b',
        accentSoft: '#e7e8ec',
        text: '#09090b'
      },
      dark: {
        rail: '#151515',
        canvas: '#191919',
        card: '#242424',
        accent: '#fafafa',
        accentSoft: '#303030',
        text: '#fafafa'
      },
    },
    cssVars: {
      light: {
        '--background': '#ffffff',
        '--foreground': '#09090b',
        '--card': '#ffffff',
        '--card-foreground': '#09090b',
        '--popover': '#ffffff',
        '--popover-foreground': '#09090b',
        '--primary': '#18181b',
        '--primary-foreground': '#fafafa',
        '--secondary': '#f4f4f5',
        '--secondary-foreground': '#18181b',
        '--muted': '#f5f5f6',
        '--muted-foreground': '#71717a',
        '--accent': '#ececef',
        '--accent-foreground': '#18181b',
        '--destructive': '#dc2626',
        '--destructive-foreground': '#fafafa',
        '--border': '#dedee3',
        '--input': '#dedee3',
        '--ring': '#a1a1aa',
        '--chart-1': '#18181b',
        '--chart-2': '#52525b',
        '--chart-3': '#71717a',
        '--chart-4': '#a1a1aa',
        '--chart-5': '#d4d4d8',
        '--sidebar': '#f1f2f4',
        '--sidebar-foreground': '#09090b',
        '--sidebar-primary': '#18181b',
        '--sidebar-primary-foreground': '#fafafa',
        '--sidebar-accent': '#e7e8ec',
        '--sidebar-accent-foreground': '#18181b',
        '--sidebar-border': '#d9dbe2',
        '--sidebar-ring': '#a1a1aa',
      },
      dark: {
        '--background': '#191919',
        '--foreground': '#fafafa',
        '--card': '#242424',
        '--card-foreground': '#fafafa',
        '--popover': '#2b2b2b',
        '--popover-foreground': '#fafafa',
        '--primary': '#fafafa',
        '--primary-foreground': '#18181b',
        '--secondary': '#2b2b2b',
        '--secondary-foreground': '#fafafa',
        '--muted': '#222222',
        '--muted-foreground': '#a1a1aa',
        '--accent': '#303030',
        '--accent-foreground': '#fafafa',
        '--destructive': '#7f1d1d',
        '--destructive-foreground': '#fafafa',
        '--border': '#3a3a3a',
        '--input': '#3a3a3a',
        '--ring': '#71717a',
        '--chart-1': '#fafafa',
        '--chart-2': '#d4d4d8',
        '--chart-3': '#a1a1aa',
        '--chart-4': '#71717a',
        '--chart-5': '#52525b',
        '--sidebar': '#151515',
        '--sidebar-foreground': '#fafafa',
        '--sidebar-primary': '#fafafa',
        '--sidebar-primary-foreground': '#18181b',
        '--sidebar-accent': '#252525',
        '--sidebar-accent-foreground': '#fafafa',
        '--sidebar-border': '#303030',
        '--sidebar-ring': '#71717a',
      },
    }
  },
  studio: {
    id: 'studio',
    label: '工作室',
    description: '深蓝主调，专业开发氛围',
    swatches: ['#3558e8', '#7aa7ff', '#f08f61'],
    preview: {
      light: {
        rail: '#304064',
        canvas: '#eef2f6',
        card: '#ffffff',
        accent: '#3558e8',
        accentSoft: '#dfe8ff',
        text: '#202b41'
      },
      dark: {
        rail: '#162032',
        canvas: '#101726',
        card: '#1d2740',
        accent: '#79a6ff',
        accentSoft: '#293650',
        text: '#f4f7ff'
      },
    },
    cssVars: {
      light: {
        '--background': '#f4f7fb',
        '--foreground': '#172033',
        '--card': '#ffffff',
        '--card-foreground': '#172033',
        '--popover': '#ffffff',
        '--popover-foreground': '#172033',
        '--primary': '#3558e8',
        '--primary-foreground': '#f8fbff',
        '--secondary': '#e9eef7',
        '--secondary-foreground': '#2a3750',
        '--muted': '#eef2f8',
        '--muted-foreground': '#6b7892',
        '--accent': '#e4ebff',
        '--accent-foreground': '#22315a',
        '--destructive': '#d65353',
        '--destructive-foreground': '#ffffff',
        '--border': '#d6dfec',
        '--input': '#d6dfec',
        '--ring': '#6f84ff',
        '--chart-1': '#3558e8',
        '--chart-2': '#00a3bf',
        '--chart-3': '#f08f61',
        '--chart-4': '#56ae74',
        '--chart-5': '#d7a53f',
        '--sidebar': '#f8fbff',
        '--sidebar-foreground': '#172033',
        '--sidebar-primary': '#3558e8',
        '--sidebar-primary-foreground': '#f8fbff',
        '--sidebar-accent': '#ebf1ff',
        '--sidebar-accent-foreground': '#20305b',
        '--sidebar-border': '#d6dfec',
      },
      dark: {
        '--background': '#101726',
        '--foreground': '#f4f7ff',
        '--card': '#1d2740',
        '--card-foreground': '#f4f7ff',
        '--popover': '#233049',
        '--popover-foreground': '#f4f7ff',
        '--primary': '#79a6ff',
        '--primary-foreground': '#0b1220',
        '--secondary': '#202c44',
        '--secondary-foreground': '#edf2ff',
        '--muted': '#192338',
        '--muted-foreground': '#92a0bd',
        '--accent': '#293650',
        '--accent-foreground': '#f5f7ff',
        '--destructive': '#ff7f8c',
        '--destructive-foreground': '#2a1116',
        '--border': '#364663',
        '--input': '#364663',
        '--ring': '#7aa7ff',
        '--chart-1': '#79a6ff',
        '--chart-2': '#67d6f3',
        '--chart-3': '#f2a272',
        '--chart-4': '#69cf8e',
        '--chart-5': '#ebc15e',
        '--sidebar': '#162032',
        '--sidebar-foreground': '#f4f7ff',
        '--sidebar-primary': '#79a6ff',
        '--sidebar-primary-foreground': '#0b1220',
        '--sidebar-accent': '#233049',
        '--sidebar-accent-foreground': '#f4f7ff',
        '--sidebar-border': '#33435f',
      },
    }
  },
  graphite: {
    id: 'graphite',
    label: '石墨',
    description: '青灰质感，沉稳护眼',
    swatches: ['#2a7b73', '#7fd4c9', '#7b8798'],
    preview: {
      light: {
        rail: '#3f4349',
        canvas: '#f3f4f5',
        card: '#ffffff',
        accent: '#2a7b73',
        accentSoft: '#dcecea',
        text: '#17191d'
      },
      dark: {
        rail: '#1d232a',
        canvas: '#171b20',
        card: '#272e36',
        accent: '#7cd8cb',
        accentSoft: '#313840',
        text: '#f5f8f7'
      },
    },
    cssVars: {
      light: {
        '--background': '#f3f4f5',
        '--foreground': '#17191d',
        '--card': '#ffffff',
        '--card-foreground': '#17191d',
        '--popover': '#ffffff',
        '--popover-foreground': '#17191d',
        '--primary': '#2a7b73',
        '--primary-foreground': '#f7fbfa',
        '--secondary': '#e8ecec',
        '--secondary-foreground': '#243133',
        '--muted': '#edf0f0',
        '--muted-foreground': '#667276',
        '--accent': '#e2ebea',
        '--accent-foreground': '#1c3131',
        '--destructive': '#c85656',
        '--destructive-foreground': '#ffffff',
        '--border': '#d5dbdc',
        '--input': '#d5dbdc',
        '--ring': '#68bfb2',
        '--chart-1': '#2a7b73',
        '--chart-2': '#4aa09a',
        '--chart-3': '#8894a4',
        '--chart-4': '#d2a66d',
        '--chart-5': '#8b6262',
        '--sidebar': '#f7f8f8',
        '--sidebar-foreground': '#17191d',
        '--sidebar-primary': '#2a7b73',
        '--sidebar-primary-foreground': '#f7fbfa',
        '--sidebar-accent': '#edf2f2',
        '--sidebar-accent-foreground': '#213536',
        '--sidebar-border': '#d5dbdc',
      },
      dark: {
        '--background': '#171b20',
        '--foreground': '#f5f8f7',
        '--card': '#272e36',
        '--card-foreground': '#f5f8f7',
        '--popover': '#2d353d',
        '--popover-foreground': '#f5f8f7',
        '--primary': '#7cd8cb',
        '--primary-foreground': '#0d1617',
        '--secondary': '#2a3139',
        '--secondary-foreground': '#eef3f2',
        '--muted': '#21272d',
        '--muted-foreground': '#a7b2b0',
        '--accent': '#313840',
        '--accent-foreground': '#f1f5f4',
        '--destructive': '#ff9898',
        '--destructive-foreground': '#2b1515',
        '--border': '#434c52',
        '--input': '#434c52',
        '--ring': '#86ddd1',
        '--chart-1': '#7cd8cb',
        '--chart-2': '#8eb7ff',
        '--chart-3': '#9ba6b7',
        '--chart-4': '#d8b57a',
        '--chart-5': '#ff9f8d',
        '--sidebar': '#1d232a',
        '--sidebar-foreground': '#f5f8f7',
        '--sidebar-primary': '#7cd8cb',
        '--sidebar-primary-foreground': '#0d1617',
        '--sidebar-accent': '#2b323a',
        '--sidebar-accent-foreground': '#f5f8f7',
        '--sidebar-border': '#414a50',
        '--sidebar-ring': '#86ddd1',
      },
    }
  },
  ocean: {
    id: 'ocean',
    label: '海洋',
    description: '深邃蓝绿，清爽通透',
    swatches: ['#0f8aa6', '#4cc9f0', '#8be3ff'],
    preview: {
      light: {
        rail: '#0f5162',
        canvas: '#eef7f8',
        card: '#ffffff',
        accent: '#0f8aa6',
        accentSoft: '#d7f0f6',
        text: '#13232a'
      },
      dark: {
        rail: '#0d202c',
        canvas: '#081823',
        card: '#122733',
        accent: '#4cc9f0',
        accentSoft: '#183342',
        text: '#eefbff'
      },
    },
    cssVars: {
      light: {
        '--background': '#eef7f8',
        '--foreground': '#13232a',
        '--card': '#ffffff',
        '--card-foreground': '#13232a',
        '--popover': '#ffffff',
        '--popover-foreground': '#13232a',
        '--primary': '#0f8aa6',
        '--primary-foreground': '#f4fdff',
        '--secondary': '#dff0f4',
        '--secondary-foreground': '#1b3540',
        '--muted': '#e7f3f6',
        '--muted-foreground': '#5c7580',
        '--accent': '#d7f0f6',
        '--accent-foreground': '#123844',
        '--destructive': '#d65f58',
        '--destructive-foreground': '#ffffff',
        '--border': '#c9e1e7',
        '--input': '#c9e1e7',
        '--ring': '#4cbad8',
        '--chart-1': '#0f8aa6',
        '--chart-2': '#4cc9f0',
        '--chart-3': '#1380b9',
        '--chart-4': '#65b58d',
        '--chart-5': '#db9f51',
        '--sidebar': '#f5fbfc',
        '--sidebar-foreground': '#13232a',
        '--sidebar-primary': '#0f8aa6',
        '--sidebar-primary-foreground': '#f4fdff',
        '--sidebar-accent': '#e2f5f8',
        '--sidebar-accent-foreground': '#123844',
        '--sidebar-border': '#c9e1e7',
      },
      dark: {
        '--background': '#081823',
        '--foreground': '#eefbff',
        '--card': '#122733',
        '--card-foreground': '#eefbff',
        '--popover': '#15303d',
        '--popover-foreground': '#eefbff',
        '--primary': '#4cc9f0',
        '--primary-foreground': '#07202a',
        '--secondary': '#13303d',
        '--secondary-foreground': '#eefbff',
        '--muted': '#0f2430',
        '--muted-foreground': '#8fb0bd',
        '--accent': '#183342',
        '--accent-foreground': '#eefbff',
        '--destructive': '#ff8d82',
        '--destructive-foreground': '#2d130f',
        '--border': '#284958',
        '--input': '#284958',
        '--ring': '#72d9ff',
        '--chart-1': '#4cc9f0',
        '--chart-2': '#8be3ff',
        '--chart-3': '#7aa8ff',
        '--chart-4': '#67d39a',
        '--chart-5': '#ffc87a',
        '--sidebar': '#0d202c',
        '--sidebar-foreground': '#eefbff',
        '--sidebar-primary': '#4cc9f0',
        '--sidebar-primary-foreground': '#07202a',
        '--sidebar-accent': '#14303d',
        '--sidebar-accent-foreground': '#eefbff',
        '--sidebar-border': '#254553',
      },
    }
  },
  forest: {
    id: 'forest',
    label: '森林',
    description: '自然绿意，宁静舒适',
    swatches: ['#2f8b57', '#6fd39a', '#98e0a0'],
    preview: {
      light: {
        rail: '#244937',
        canvas: '#f4f8f4',
        card: '#ffffff',
        accent: '#2f8b57',
        accentSoft: '#e1f1e6',
        text: '#16221b'
      },
      dark: {
        rail: '#122119',
        canvas: '#0d1913',
        card: '#17261d',
        accent: '#6fd39a',
        accentSoft: '#1d3025',
        text: '#effbf3'
      },
    },
    cssVars: {
      light: {
        '--background': '#f4f8f4',
        '--foreground': '#16221b',
        '--card': '#ffffff',
        '--card-foreground': '#16221b',
        '--popover': '#ffffff',
        '--popover-foreground': '#16221b',
        '--primary': '#2f8b57',
        '--primary-foreground': '#f6fff8',
        '--secondary': '#e5efe7',
        '--secondary-foreground': '#22372a',
        '--muted': '#ebf3ec',
        '--muted-foreground': '#67796d',
        '--accent': '#e1f1e6',
        '--accent-foreground': '#1d3a28',
        '--destructive': '#c95e5e',
        '--destructive-foreground': '#ffffff',
        '--border': '#d6e3d8',
        '--input': '#d6e3d8',
        '--ring': '#59b87d',
        '--chart-1': '#2f8b57',
        '--chart-2': '#64b287',
        '--chart-3': '#96c36b',
        '--chart-4': '#dfb35c',
        '--chart-5': '#c77e5c',
        '--sidebar': '#f8fbf8',
        '--sidebar-foreground': '#16221b',
        '--sidebar-primary': '#2f8b57',
        '--sidebar-primary-foreground': '#f6fff8',
        '--sidebar-accent': '#edf5ef',
        '--sidebar-accent-foreground': '#1d3a28',
        '--sidebar-border': '#d6e3d8',
      },
      dark: {
        '--background': '#0d1913',
        '--foreground': '#effbf3',
        '--card': '#17261d',
        '--card-foreground': '#effbf3',
        '--popover': '#1c2d22',
        '--popover-foreground': '#effbf3',
        '--primary': '#6fd39a',
        '--primary-foreground': '#0b1d13',
        '--secondary': '#1a2b20',
        '--secondary-foreground': '#effbf3',
        '--muted': '#122118',
        '--muted-foreground': '#93ae9b',
        '--accent': '#1d3025',
        '--accent-foreground': '#effbf3',
        '--destructive': '#ff9494',
        '--destructive-foreground': '#2b1515',
        '--border': '#31523f',
        '--input': '#31523f',
        '--ring': '#88e2af',
        '--chart-1': '#6fd39a',
        '--chart-2': '#98e0a0',
        '--chart-3': '#b9d665',
        '--chart-4': '#f0c275',
        '--chart-5': '#ff9d78',
        '--sidebar': '#122119',
        '--sidebar-foreground': '#effbf3',
        '--sidebar-primary': '#6fd39a',
        '--sidebar-primary-foreground': '#0b1d13',
        '--sidebar-accent': '#1a2c21',
        '--sidebar-accent-foreground': '#effbf3',
        '--sidebar-border': '#2e4d3b',
      },
    }
  },
  dawn: {
    id: 'dawn',
    label: '黎明',
    description: '暖橙色调，温和明亮',
    swatches: ['#ca6a33', '#ffb27d', '#ffd8a8'],
    preview: {
      light: {
        rail: '#6a402f',
        canvas: '#fbf6f2',
        card: '#ffffff',
        accent: '#ca6a33',
        accentSoft: '#f9e5da',
        text: '#2b1d19'
      },
      dark: {
        rail: '#2a1911',
        canvas: '#22140e',
        card: '#312016',
        accent: '#ffb27d',
        accentSoft: '#3f291c',
        text: '#fff4eb'
      },
    },
    cssVars: {
      light: {
        '--background': '#fbf6f2',
        '--foreground': '#2b1d19',
        '--card': '#ffffff',
        '--card-foreground': '#2b1d19',
        '--popover': '#ffffff',
        '--popover-foreground': '#2b1d19',
        '--primary': '#ca6a33',
        '--primary-foreground': '#fffaf7',
        '--secondary': '#f3e8df',
        '--secondary-foreground': '#473025',
        '--muted': '#f7eee7',
        '--muted-foreground': '#7f665c',
        '--accent': '#f9e5da',
        '--accent-foreground': '#5f3824',
        '--destructive': '#cc6258',
        '--destructive-foreground': '#ffffff',
        '--border': '#ead6cb',
        '--input': '#ead6cb',
        '--ring': '#e99568',
        '--chart-1': '#ca6a33',
        '--chart-2': '#ff9a63',
        '--chart-3': '#d79c52',
        '--chart-4': '#b49068',
        '--chart-5': '#8f6464',
        '--sidebar': '#fdf9f6',
        '--sidebar-foreground': '#2b1d19',
        '--sidebar-primary': '#ca6a33',
        '--sidebar-primary-foreground': '#fffaf7',
        '--sidebar-accent': '#fbede4',
        '--sidebar-accent-foreground': '#5f3824',
        '--sidebar-border': '#ead6cb',
      },
      dark: {
        '--background': '#22140e',
        '--foreground': '#fff4eb',
        '--card': '#312016',
        '--card-foreground': '#fff4eb',
        '--popover': '#382519',
        '--popover-foreground': '#fff4eb',
        '--primary': '#ffb27d',
        '--primary-foreground': '#341a0e',
        '--secondary': '#372418',
        '--secondary-foreground': '#fff4eb',
        '--muted': '#2c1c13',
        '--muted-foreground': '#c7ac9b',
        '--accent': '#3f291c',
        '--accent-foreground': '#fff4eb',
        '--destructive': '#ff9d8b',
        '--destructive-foreground': '#331611',
        '--border': '#5d3d29',
        '--input': '#5d3d29',
        '--ring': '#ffbf90',
        '--chart-1': '#ffb27d',
        '--chart-2': '#ffd8a8',
        '--chart-3': '#f3c66b',
        '--chart-4': '#d6a07e',
        '--chart-5': '#ff9b8b',
        '--sidebar': '#2a1911',
        '--sidebar-foreground': '#fff4eb',
        '--sidebar-primary': '#ffb27d',
        '--sidebar-primary-foreground': '#341a0e',
        '--sidebar-accent': '#392519',
        '--sidebar-accent-foreground': '#fff4eb',
        '--sidebar-border': '#593924',
      },
    }
  },
}

const APP_THEME_PRESET_IDS: AppThemePreset[] = ['mulberry', 'studio', 'graphite', 'ocean', 'forest', 'dawn']
export const APP_THEME_PRESETS = APP_THEME_PRESET_IDS.map((id) => PRESET_DEFINITIONS[id])

const ALL_THEME_CSS_VAR_KEYS = Array.from(
  new Set(
    APP_THEME_PRESETS.flatMap((preset) =>
      Object.values(preset.cssVars).flatMap((vars) => Object.keys(vars))
    )
  )
)

export function resolveAppThemeMode(value?: string | null): AppThemeMode {
  return value === 'light' ? 'light' : 'dark'
}

export function getThemePresetDefinition(preset: AppThemePreset): ThemePresetDefinition {
  return PRESET_DEFINITIONS[preset] ?? PRESET_DEFINITIONS[DEFAULT_APP_THEME_PRESET]
}

export function applyThemePresetCssVars(
  root: HTMLElement,
  preset: AppThemePreset,
  mode: AppThemeMode
): void {
  const cssVars = getThemePresetDefinition(preset).cssVars[mode]
  for (const key of ALL_THEME_CSS_VAR_KEYS) {
    root.style.removeProperty(key)
  }
  for (const [key, value] of Object.entries(cssVars)) {
    root.style.setProperty(key, value)
  }
}
