import type { ThemePresetDefinition } from './types'
import { createTerminalTheme } from './terminal-theme'

export const mulberryPreset: ThemePresetDefinition =   {
    id: 'mulberry',
    labelKey: 'general.themePreset.presets.mulberry.label',
    descriptionKey: 'general.themePreset.presets.mulberry.desc',
    swatches: ['#18181b', '#71717a', '#fafafa'],
    preview: {
      light: {
        rail: '#f1f2f4',
        canvas: '#ffffff',
        card: '#ffffff',
        accent: '#18181b',
        accentSoft: '#e7e8ec',
        text: '#09090b'
      },
      dark: {
        rail: '#151515',
        canvas: '#191919',
        card: '#242424',
        accent: '#fafafa',
        accentSoft: '#303030',
        text: '#fafafa'
      }
    },
    cssVars: {
      light: {
        '--background': '#ffffff',
        '--foreground': '#09090b',
        '--card': '#ffffff',
        '--card-foreground': '#09090b',
        '--popover': '#ffffff',
        '--popover-foreground': '#09090b',
        '--primary': '#18181b',
        '--primary-foreground': '#fafafa',
        '--secondary': '#f4f4f5',
        '--secondary-foreground': '#18181b',
        '--muted': '#f5f5f6',
        '--muted-foreground': '#71717a',
        '--accent': '#ececef',
        '--accent-foreground': '#18181b',
        '--destructive': '#dc2626',
        '--destructive-foreground': '#fafafa',
        '--border': '#dedee3',
        '--input': '#dedee3',
        '--ring': '#a1a1aa',
        '--chart-1': '#18181b',
        '--chart-2': '#52525b',
        '--chart-3': '#71717a',
        '--chart-4': '#a1a1aa',
        '--chart-5': '#d4d4d8',
        '--sidebar': '#f1f2f4',
        '--sidebar-foreground': '#09090b',
        '--sidebar-primary': '#18181b',
        '--sidebar-primary-foreground': '#fafafa',
        '--sidebar-accent': '#e7e8ec',
        '--sidebar-accent-foreground': '#18181b',
        '--sidebar-border': '#d9dbe2',
        '--sidebar-ring': '#a1a1aa',
        '--workspace-titlebar-bg': '#ffffff',
        '--workspace-titlebar-border': '#e6e6ea',
        '--workspace-titlebar-button-hover': '#f0f0f2',
        '--workspace-titlebar-toolgroup-bg': '#f7f7f8',
        '--workspace-titlebar-toolgroup-border': '#dedee3',
        '--workspace-titlebar-toolbutton-hover': '#ededf0',
        '--workspace-titlebar-toolbutton-active': '#e4e5e9',
        '--workspace-sidebar-divider': '#d9dbe2',
        '--workspace-sidebar-section-border': '#e0e1e6',
        '--workspace-sidebar-row-hover-bg': '#e8e9ed',
        '--workspace-sidebar-row-hover-border': '#d8dae1',
        '--workspace-sidebar-row-active-bg': '#dedfe5',
        '--workspace-sidebar-row-active-border': '#cfd2da',
        '--workspace-sidebar-row-active-shadow': '0 10px 18px -16px rgba(24, 24, 27, 0.12)',
        '--activity-card-bg': '#ffffff',
        '--activity-card-border': '#dedee3',
        '--activity-card-divider': '#ececf0',
        '--activity-card-header-hover': '#f0f0f2',
        '--activity-card-shadow': '0 14px 28px -22px rgba(24, 24, 27, 0.12)',
        '--composer-shell-top': '#ffffff',
        '--composer-shell-bottom': '#ffffff',
        '--composer-shell-border': '#dedee3',
        '--composer-shell-border-focus': 'color-mix(in srgb, #a1a1aa 28%, #dedee3)',
        '--composer-shell-shadow':
          '0 14px 30px -24px rgba(24, 24, 27, 0.12), 0 1px 2px rgba(24, 24, 27, 0.06)',
        '--composer-shell-shadow-focus':
          '0 18px 34px -24px rgba(24, 24, 27, 0.14), 0 0 0 3px rgba(161, 161, 170, 0.12)',
        '--composer-toolbar-border': '#ededf0',
        '--composer-panel-bg': '#ffffff',
        '--composer-panel-border': '#dedee3',
        '--composer-panel-shadow':
          '0 20px 36px -28px rgba(24, 24, 27, 0.12), 0 1px 2px rgba(24, 24, 27, 0.06)',
        '--composer-control-bg-hover': '#f0f0f2',
        '--composer-control-active-text': '#09090b',
        '--composer-send-start': '#18181b',
        '--composer-send-end': '#18181b',
        '--composer-send-foreground': '#fafafa',
        '--composer-chip-border': '#dedee3',
        '--composer-chip-text': '#52525b',
        '--composer-chip-hover': '#f0f0f2',
        '--composer-drop-bg': '#e8e9ed'
      },
      dark: {
        '--background': '#191919',
        '--foreground': '#fafafa',
        '--card': '#242424',
        '--card-foreground': '#fafafa',
        '--popover': '#2b2b2b',
        '--popover-foreground': '#fafafa',
        '--primary': '#fafafa',
        '--primary-foreground': '#18181b',
        '--secondary': '#2b2b2b',
        '--secondary-foreground': '#fafafa',
        '--muted': '#222222',
        '--muted-foreground': '#a1a1aa',
        '--accent': '#303030',
        '--accent-foreground': '#fafafa',
        '--destructive': '#7f1d1d',
        '--destructive-foreground': '#fafafa',
        '--border': '#3a3a3a',
        '--input': '#3a3a3a',
        '--ring': '#71717a',
        '--chart-1': '#fafafa',
        '--chart-2': '#d4d4d8',
        '--chart-3': '#a1a1aa',
        '--chart-4': '#71717a',
        '--chart-5': '#52525b',
        '--sidebar': '#151515',
        '--sidebar-foreground': '#fafafa',
        '--sidebar-primary': '#fafafa',
        '--sidebar-primary-foreground': '#18181b',
        '--sidebar-accent': '#252525',
        '--sidebar-accent-foreground': '#fafafa',
        '--sidebar-border': '#303030',
        '--sidebar-ring': '#71717a',
        '--workspace-titlebar-bg': '#191919',
        '--workspace-titlebar-border': '#303030',
        '--workspace-titlebar-button-hover': '#303030',
        '--workspace-titlebar-toolgroup-bg': '#242424',
        '--workspace-titlebar-toolgroup-border': '#3a3a3a',
        '--workspace-titlebar-toolbutton-hover': '#303030',
        '--workspace-titlebar-toolbutton-active': '#3a3a3a',
        '--workspace-sidebar-divider': '#303030',
        '--workspace-sidebar-section-border': '#303030',
        '--workspace-sidebar-row-hover-bg': '#303030',
        '--workspace-sidebar-row-hover-border': '#3a3a3a',
        '--workspace-sidebar-row-active-bg': '#3a3a3a',
        '--workspace-sidebar-row-active-border': '#4a4a4a',
        '--workspace-sidebar-row-active-shadow': '0 14px 24px -22px rgba(0, 0, 0, 0.32)',
        '--activity-card-bg': '#242424',
        '--activity-card-border': '#3a3a3a',
        '--activity-card-divider': '#303030',
        '--activity-card-header-hover': '#303030',
        '--activity-card-shadow': '0 18px 32px -24px rgba(0, 0, 0, 0.36)',
        '--composer-shell-top': '#303030',
        '--composer-shell-bottom': '#303030',
        '--composer-shell-border': '#3a3a3a',
        '--composer-shell-border-focus': 'color-mix(in srgb, #71717a 28%, #3a3a3a)',
        '--composer-shell-shadow':
          '0 18px 32px -24px rgba(0, 0, 0, 0.34), 0 1px 2px rgba(0, 0, 0, 0.2)',
        '--composer-shell-shadow-focus':
          '0 22px 36px -24px rgba(0, 0, 0, 0.38), 0 0 0 3px rgba(113, 113, 122, 0.12)',
        '--composer-toolbar-border': '#3a3a3a',
        '--composer-panel-bg': '#303030',
        '--composer-panel-border': '#3a3a3a',
        '--composer-panel-shadow':
          '0 22px 40px -28px rgba(0, 0, 0, 0.42), 0 1px 2px rgba(0, 0, 0, 0.22)',
        '--composer-control-bg-hover': '#3a3a3a',
        '--composer-control-active-text': '#fafafa',
        '--composer-send-start': '#fafafa',
        '--composer-send-end': '#fafafa',
        '--composer-send-foreground': '#18181b',
        '--composer-chip-border': '#3a3a3a',
        '--composer-chip-text': '#d4d4d8',
        '--composer-chip-hover': '#3a3a3a',
        '--composer-drop-bg': '#3a3a3a'
      }
    },
    terminal: {
      light: createTerminalTheme({
        background: '#ffffff',
        foreground: '#09090b',
        selectionBackground: 'rgba(24, 24, 27, 0.12)',
        cursor: '#18181b',
        black: '#09090b',
        red: '#ef4444',
        green: '#22c55e',
        yellow: '#eab308',
        blue: '#3b82f6',
        magenta: '#a855f7',
        cyan: '#06b6d4',
        white: '#e4e4e7',
        brightBlack: '#71717a',
        brightRed: '#f87171',
        brightGreen: '#4ade80',
        brightYellow: '#facc15',
        brightBlue: '#60a5fa',
        brightMagenta: '#c084fc',
        brightCyan: '#22d3ee',
        brightWhite: '#ffffff'
      }),
      dark: createTerminalTheme({
        background: '#09090b',
        foreground: '#fafafa',
        selectionBackground: 'rgba(250, 250, 250, 0.16)',
        cursor: '#fafafa',
        black: '#09090b',
        red: '#f87171',
        green: '#4ade80',
        yellow: '#facc15',
        blue: '#60a5fa',
        magenta: '#c084fc',
        cyan: '#22d3ee',
        white: '#fafafa',
        brightBlack: '#71717a',
        brightRed: '#fca5a5',
        brightGreen: '#86efac',
        brightYellow: '#fde047',
        brightBlue: '#93c5fd',
        brightMagenta: '#d8b4fe',
        brightCyan: '#67e8f9',
        brightWhite: '#ffffff'
      })
    },
    ssh: {
      light: {
        libraryFrameStart: '#ffffff',
        libraryFrameEnd: '#f7f7f8',
        libraryBorder: '#e6e6ea',
        libraryText: '#18181b',
        connectFrame: '#fafafa',
        connectBorder: '#e4e4e7',
        connectText: '#52525b',
        terminalFrame: '#18181b',
        terminalBorder: 'rgba(255,255,255,0.08)',
        terminalText: '#fafafa',
        canvas: '#fafafa',
        canvasSubtle: '#ffffff',
        terminalCanvas: '#ffffff',
        panel: '#18181b',
        panelStrong: '#09090b',
        panelBorder: 'rgba(255,255,255,0.08)',
        surface: '#ffffff',
        surfaceStrong: '#fafafa',
        text: '#09090b',
        muted: '#71717a',
        accent: '#18181b',
        accentSoft: '#f4f4f5',
        accentContrast: '#fafafa',
        success: '#16a34a',
        successSoft: '#f0fdf4',
        warning: '#ca8a04',
        warningSoft: '#fefce8',
        danger: '#dc2626',
        dangerSoft: '#fef2f2',
        badge: '#18181b',
        libraryPill: '#f4f4f5',
        libraryPillActive: '#e4e4e7',
        libraryPillText: '#52525b',
        libraryPillActiveText: '#18181b',
        connectPill: '#f4f4f5',
        connectPillActive: '#e4e4e7',
        connectPillText: '#52525b',
        connectPillActiveText: '#18181b',
        terminalPill: 'rgba(255,255,255,0.08)',
        terminalPillActive: '#27272a',
        terminalPillText: '#e4e4e7',
        terminalPillActiveText: '#fafafa'
      },
      dark: {
        libraryFrameStart: '#09090b',
        libraryFrameEnd: '#18181b',
        libraryBorder: 'rgba(255,255,255,0.08)',
        libraryText: '#fafafa',
        connectFrame: '#09090b',
        connectBorder: '#27272a',
        connectText: '#a1a1aa',
        terminalFrame: '#09090b',
        terminalBorder: 'rgba(255,255,255,0.08)',
        terminalText: '#fafafa',
        canvas: '#09090b',
        canvasSubtle: '#111113',
        terminalCanvas: '#09090b',
        panel: '#18181b',
        panelStrong: '#111113',
        panelBorder: 'rgba(255,255,255,0.08)',
        surface: '#18181b',
        surfaceStrong: '#202024',
        text: '#fafafa',
        muted: '#a1a1aa',
        accent: '#fafafa',
        accentSoft: '#27272a',
        accentContrast: '#18181b',
        success: '#4ade80',
        successSoft: '#052e16',
        warning: '#facc15',
        warningSoft: '#422006',
        danger: '#f87171',
        dangerSoft: '#450a0a',
        badge: '#fafafa',
        libraryPill: 'rgba(255,255,255,0.08)',
        libraryPillActive: 'rgba(255,255,255,0.14)',
        libraryPillText: '#e4e4e7',
        libraryPillActiveText: '#ffffff',
        connectPill: '#18181b',
        connectPillActive: '#27272a',
        connectPillText: '#a1a1aa',
        connectPillActiveText: '#fafafa',
        terminalPill: 'rgba(255,255,255,0.08)',
        terminalPillActive: '#27272a',
        terminalPillText: '#e4e4e7',
        terminalPillActiveText: '#fafafa'
      }
    }
  };
