const MAX_TRACKED_TOOL_CALLS = 200
const MAX_COMPLETED_SUBAGENTS = 30
const MAX_STREAMING_TEXT_CHARS = 8_000
const MAX_TOOL_INPUT_PREVIEW_CHARS = 6_000
const MAX_TOOL_OUTPUT_TEXT_CHARS = 8_000
const MAX_TOOL_ERROR_CHARS = 2_000
const MAX_IMAGE_BASE64_CHARS = 4_096
const MAX_BACKGROUND_PROCESS_OUTPUT_CHARS = 12_000
const MAX_BACKGROUND_PROCESS_ENTRIES = 60
const MAX_RUN_CHANGESETS = 40
const BACKGROUND_PROCESS_OUTPUT_FLUSH_MS = 80
const AGENT_STORE_STORAGE_KEY = 'opencowork-agent'
const LEGACY_AGENT_HISTORY_STORAGE_KEY = 'opencowork-agent-history'
const AGENT_HISTORY_PERSIST_DEBOUNCE_MS = 500
const SHELL_TOOL_NAMES = new Set(['Bash', 'Shell', 'PowerShell'])

export {
  MAX_TRACKED_TOOL_CALLS,
  MAX_COMPLETED_SUBAGENTS,
  MAX_STREAMING_TEXT_CHARS,
  MAX_TOOL_INPUT_PREVIEW_CHARS,
  MAX_TOOL_OUTPUT_TEXT_CHARS,
  MAX_TOOL_ERROR_CHARS,
  MAX_IMAGE_BASE64_CHARS,
  MAX_BACKGROUND_PROCESS_OUTPUT_CHARS,
  MAX_BACKGROUND_PROCESS_ENTRIES,
  MAX_RUN_CHANGESETS,
  BACKGROUND_PROCESS_OUTPUT_FLUSH_MS,
  AGENT_STORE_STORAGE_KEY,
  LEGACY_AGENT_HISTORY_STORAGE_KEY,
  AGENT_HISTORY_PERSIST_DEBOUNCE_MS,
  SHELL_TOOL_NAMES
}
